backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: false

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://photoblog-hildemorin.netlify.app

collections:
  - name: "about"
    label: "About"
    folder: "content/about"
    path: "about"
    create: false
    delete: false
    media_folder: ""
    fields:
      - {label: "Id", name: "id", widget: "hidden", required: true}
      - {label: "Banner image", name: "banner", widget: "image" , allow_multiple: false, required: true}
      - {label: "About", name: "body", widget: "markdown"}
